[build-system]
requires = [
  "setuptools>=69",
  "setuptools-scm>=8"
]

[project]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy"
]
dependencies = [
]
description = "Peek into pickle files without importing unknown dependencies"
dynamic = [
  "version"
]
keywords = [
  "pickle",
  "serialization",
  "deserialization"
]
license = "Apache-2.0"
license-files = ["LICENSE"]
name = "peekle"
readme = "README.md"
requires-python = ">=3.9"

[project.optional-dependencies]
test = ["pytest>=7"]

[project.scripts]
peekle = "peekle.__main__:main"

[project.urls]
Homepage = "https://github.com/ecmwf/peekle/"
Repository = "https://github.com/ecmwf/peekle/"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools_scm]
fallback_version = "0.0.0"
version_file = "src/peekle/_version.py"
